#!/usr/bin/env python3
"""Writes UI/TrixieVoiceLengths.lua: how many seconds each Trixie clip runs.

The client cannot say how long a sound is, and Lobby:PlayTrixieVoice needs to
know, to tell whether she is still speaking: a line that comes up while she is
drops instead of playing over her. Run after any clips change (regen_v4.py
does not run it for you):

  python tools/voice_lengths.py

Needs ffmpeg (FFMPEG, PATH, or the copy in Lian-Li's L-Connect).
"""
import os, re, shutil, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SOUNDS = os.path.join(ROOT, "Sounds", "Trixie")
OUT = os.path.join(ROOT, "UI", "TrixieVoiceLengths.lua")
LCONNECT = r"C:\Program Files\Lian-Li\L-Connect 3\x64\ffmpeg.exe"


def find_ffmpeg():
    for c in (os.environ.get("FFMPEG"), shutil.which("ffmpeg"), LCONNECT):
        if c and os.path.isfile(c):
            return c
    sys.exit("ffmpeg not found: set FFMPEG")


def seconds(ffmpeg, path):
    r = subprocess.run([ffmpeg, "-hide_banner", "-i", path], capture_output=True, text=True)
    m = re.search(r"Duration: (\d+):(\d+):([\d.]+)", r.stderr)
    return int(m.group(1)) * 3600 + int(m.group(2)) * 60 + float(m.group(3)) if m else None


def main():
    ffmpeg = find_ffmpeg()
    lengths = {}
    for f in sorted(os.listdir(SOUNDS)):
        base, ext = os.path.splitext(f)
        if ext.lower() != ".ogg" or not base.startswith("trix_"):
            continue
        s = seconds(ffmpeg, os.path.join(SOUNDS, f))
        if s:
            lengths[base] = s
    lines = ["-- Generated by tools/voice_lengths.py from Sounds/Trixie. Do not edit:",
             "-- run python tools/voice_lengths.py after any clip changes.",
             "-- Seconds each clip runs, by file name without its extension.",
             "ChairfacesCasino = ChairfacesCasino or {}",
             "ChairfacesCasino.TRIXIE_LENGTHS = {"]
    for name in sorted(lengths):
        lines.append(f'    ["{name}"] = {lengths[name]:.2f},')
    lines.append("}")
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"{len(lengths)} clip lengths written to {OUT}")


if __name__ == "__main__":
    main()
