-- Generated by tools/gen_trixie_anims.py - do not edit by hand.
-- Trixie's animated clips (AutoSprite sheets in Textures/dealer/anim/), read by UI/Trixie.lua.
local BJ = ChairfacesCasino
BJ.TrixieClips = {
}
